[package]
name = "selvedge-router"
edition = "2024"
publish = false

[dependencies]
selvedge-api = { path = "../api" }
selvedge-command-model = { path = "../command-model" }
selvedge-core = { path = "../core" }
selvedge-db = { path = "../db" }
selvedge-domain-model = { path = "../domain-model" }
selvedge-task-runtime-factory = { path = "../task-runtime-factory" }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync"] }

[dev-dependencies]
selvedge-domain-model = { path = "../domain-model" }
selvedge-test-support = { path = "../test-support", features = ["db-fixtures"] }
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }

[lints]
workspace = true
