[package]
name = "selvedge-model-providers"
edition = "2024"
publish = false

[dependencies]
selvedge-config-model = { path = "../config-model" }
selvedge-model-credentials = { path = "../model-credentials" }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
