[package]
name = "selvedge-task-runtime-factory"
edition = "2024"
publish = false

[dependencies]
selvedge-command-model = { path = "../command-model" }
selvedge-core = { path = "../core" }
selvedge-db = { path = "../db" }

[dev-dependencies]
selvedge-domain-model = { path = "../domain-model" }
selvedge-test-support = { path = "../test-support", features = ["db-fixtures"] }
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }

[lints]
workspace = true
