[package]
name = "selvedge-client"
edition = "2024"
publish = false

[dependencies]
async-stream = { workspace = true }
bytes = { workspace = true }
futures-core = { workspace = true }
futures-util = { workspace = true }
http = { workspace = true }
reqwest = { version = "0.12.24", default-features = false, features = ["rustls-tls", "stream"] }
rustls-pemfile = "2.2.0"
selvedge-config = { path = "../config" }
selvedge-logging = { path = "../logging" }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["time"] }
url = { workspace = true }
zstd = "0.13.3"

[dev-dependencies]
axum = { workspace = true }
rcgen = "0.14.5"
selvedge-test-support = { path = "../test-support", features = ["config", "http"] }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
tokio-rustls = "0.26.4"

[lints]
workspace = true
