[package]
name = "selvedge-config"
edition = "2024"
publish = false

[dependencies]
serde = { workspace = true, features = ["derive"] }
selvedge-config-model = { path = "../config-model" }
tempfile = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
toml_edit = { version = "0.22.27", default-features = false, features = ["parse"] }

[lints]
workspace = true
