[package]
name = "selvedge-client-sync"
edition = "2024"
publish = false

[dependencies]
selvedge-command-model = { path = "../command-model" }
selvedge-domain-model = { path = "../domain-model" }
tokio = { workspace = true, features = ["macros", "rt", "sync"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }

[lints]
workspace = true
