[package]
name = "chatgpt-api"
edition = "2024"
publish = false

[dependencies]
bytes = { workspace = true }
futures-core = { workspace = true }
futures-util = { workspace = true }
http = { workspace = true }
httpdate = "1.0.3"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["arbitrary_precision"] }
selvedge-client = { path = "../client" }
selvedge-config = { path = "../config" }
selvedge-config-model = { path = "../config-model" }
selvedge-domain-model = { path = "../domain-model" }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync", "time"] }
url = { workspace = true }

[dependencies.chatgpt-auth]
path = "../chatgpt-auth"
package = "chatgpt-auth"

[dev-dependencies]
async-stream = { workspace = true }
axum = { workspace = true, features = ["ws"] }
selvedge-logging = { path = "../logging" }
selvedge-test-support = { path = "../test-support", features = ["chatgpt-auth", "config", "http"] }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread", "sync", "time"] }

[lints]
workspace = true
