[package]
name = "selvedge-systemd"
edition = "2024"
publish = false

[dependencies]
tokio = { version = "1.42.0", features = ["io-util", "process", "rt", "time"] }

[dev-dependencies]
tokio = { version = "1.42.0", features = ["io-util", "macros", "process", "rt", "sync", "time"] }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
dbg_macro = "deny"
todo = "deny"
unwrap_used = "deny"
