[package]
name = "selvedge-events"
edition = "2024"
publish = false

[dependencies]
selvedge-command-model = { path = "../command-model" }
tokio = { workspace = true, features = ["rt", "sync"] }

[dev-dependencies]
selvedge-domain-model = { path = "../domain-model" }
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }

[lints]
workspace = true
