[package]
name = "selvedge-web"
edition = "2024"
publish = false

[dependencies]
futures-core = "0.3.31"
selvedge-local-protocol = { path = "../local-protocol" }
tokio = { version = "1.42.0", features = ["rt", "sync"] }
tokio-stream = { version = "0.1.17", features = ["sync"] }

[dev-dependencies]
futures-util = "0.3.31"
serde_json = "1.0.145"
tokio = { version = "1.42.0", features = ["macros", "rt", "sync", "time"] }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
dbg_macro = "deny"
todo = "deny"
unwrap_used = "deny"
