[package]
name = "selvedge-web"
edition = "2024"
publish = false

[dependencies]
futures-util = { workspace = true }
bytes = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true, features = ["http1", "server"] }
hyper-util = { workspace = true, features = ["tokio"] }
futures-core = { workspace = true }
selvedge-local-protocol = { path = "../local-protocol" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt", "sync", "time"] }
tokio-stream = { workspace = true, features = ["sync"] }

[dev-dependencies]
selvedge-local-client = { path = "../local-client" }
selvedge-test-support = { path = "../test-support", features = ["http"] }
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt", "sync", "time"] }

[lints]
workspace = true
