[package]
name = "selvedge-tui"
edition = "2024"
publish = false

[dependencies]
futures-util = "0.3.31"
selvedge-local-client = { path = "../local-client" }
selvedge-local-protocol = { path = "../local-protocol" }
tokio = { version = "1.42.0", features = ["time"] }

[dev-dependencies]
serde_json = "1.0.135"
selvedge-test-support = { path = "../test-support", features = ["local-transport"] }
tokio = { version = "1.42.0", features = ["macros", "rt", "sync"] }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
dbg_macro = "deny"
todo = "deny"
unwrap_used = "deny"
