[package]
name = "selvedge-db"
edition = "2024"
publish = false

[dependencies]
rusqlite = { workspace = true, features = ["bundled"] }
selvedge-domain-model = { path = "../domain-model" }
serde_json = { workspace = true, features = ["arbitrary_precision"] }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
