[package]
name = "selvedge-core"
edition = "2024"
publish = false

[dependencies]
selvedge-command-model = { path = "../command-model" }
selvedge-db = { path = "../db" }
selvedge-domain-model = { path = "../domain-model" }
serde_json = { workspace = true, features = ["arbitrary_precision"] }
tokio = { workspace = true, features = ["macros", "rt", "sync"] }
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
rusqlite = { workspace = true, features = ["bundled"] }
tempfile = { workspace = true }
selvedge-test-support = { path = "../test-support", features = ["db-fixtures"] }
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }

[lints]
workspace = true
