[package]
name = "selvedge-model-credentials"
edition = "2024"
publish = false

[dependencies]
fs2 = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
selvedge-config-model = { path = "../config-model" }
selvedge-config = { path = "../config" }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync"] }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
