[package]
name = "selvedge-server"
edition = "2024"
publish = false

[dependencies]
fs2 = { workspace = true }
futures-core = { workspace = true }
selvedge-api = { path = "../api" }
selvedge-client-sync = { path = "../client-sync" }
selvedge-command-model = { path = "../command-model" }
selvedge-config = { path = "../config" }
selvedge-config-model = { path = "../config-model" }
selvedge-core = { path = "../core" }
selvedge-db = { path = "../db" }
selvedge-domain-model = { path = "../domain-model" }
selvedge-events = { path = "../events" }
selvedge-harness = { path = "../harness" }
selvedge-local-protocol = { path = "../local-protocol" }
selvedge-logging = { path = "../logging" }
selvedge-router = { path = "../router" }
selvedge-web = { path = "../web" }
tokio = { workspace = true, features = ["fs", "macros", "rt", "sync"] }

[dev-dependencies]
futures-util = { workspace = true }
serde_json = { workspace = true }
selvedge-test-support = { path = "../test-support", features = ["http"] }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }

[lints]
workspace = true
